apiVersion: v1
kind: Service
metadata:
  name: mittekugel
  labels:
    app: mittekugel
    env: staging
spec:
  type: NodePort
  selector:
    app: mittekugel
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
